title: Blog of Paper Note # The title of your blog
email: yanliangfdu@gmail.com # Your email address
description: >- # A description of your website
  This is my personal blog where I write about my research.
baseurl: "" # The base path of your site. If your site's address is directly at username.github.io, you can leave this empty
url: "http://yanliang3612.github.io" # The URL of your GitHub Pages site

# Build settings
markdown: kramdown # The Markdown engine used for converting markdown files
theme: minima # The theme for your site. Replace "minima" with any other theme you might want to use
plugins:
  - jekyll-feed # Plugins you want to use. jekyll-feed generates an RSS feed for your posts
  
markdown: kramdown
kramdown:
  math_engine: mathjax
