title: Blog of Paper Note 
email: yanliangfdu@gmail.com
description: >- # 这是您网站的描述
  This is my personal blog where I write about my research.
baseurl: "" # 站点的基础路径，如果您的网站地址直接是 username.github.io 则可以保留为空
url: "http://username.github.io" # 您的 GitHub Pages 网址

# 构建设置
markdown: kramdown
theme: minima # 或者您想要的任何其他主题
plugins:
  - jekyll-feed

